version: "3.3"
services:
  web:
    container_name: webserver
    build: .
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: /home/logs
        target: /usr/share/nginx/html/
